services:
  jupyter:
    build: .
    image: mf810-project
    container_name: mf810-project
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - SPARK_DRIVER_MEMORY=7g
      - JUPYTER_ENABLE_LAB=yes
